export const CHANGE_CLIENT_WH = 'CHANGE_CLIENT_WH'
export const CHANGE_SEARCHKEYWORDS = 'CHANGE_SEARCHKEYWORDS'
export const CHANGE_ARTICLE = 'CHANGE_ARTICLE'
export const CHANGE_ARTICLE_PAGENUM = 'CHANGE_ARTICLE_PAGENUM'
export const CHANGE_ARTICLE_PAGESIZE = 'CHANGE_ARTICLE_PAGESIZE'
export const CHANGE_ARTICLE_CURPAGE = 'CHANGE_ARTICLE_CURPAGE'

